### ISSUE TITLE
回调问题

### ISSUE THREAD

**Issue by jasonchou3** [jpush/jshare-react-native#10]
//文档推荐：无效
- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url{
  [JSHAREService handleOpenUrl:url];
  return YES;
}

//非文档推荐：有效
// Add this above the `@end`:
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  [JSHAREService handleOpenUrl:url];

    return [RCTLinkingManager application:application openURL:url
                        sourceApplication:sourceApplication annotation:annotation];
}

何解？

**Comment by huangminlinux** [comment]
OK 已更新文档。下面的方法在 iOS 9 才有效，没注意。
```
- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url{
[JSHAREService handleOpenUrl:url];
return YES;
}
```

iOS 10 还需要添加如下代码。
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  [JSHAREService handleOpenUrl:url];
  return YES;
}
```
