### ISSUE TITLE
import cn.jiguang.share.android.api.JShareInterface  找不到这个包

### ISSUE THREAD

**Issue by yunuo-tech** [jpush/jshare-react-native#101]
import cn.jiguang.share.android.api.JShareInterface
编译的时候报错了，这个包不存在
![image](https://user-images.githubusercontent.com/5960864/47265374-a01f1f80-d559-11e8-98c4-0daf80ee47c9.png)

![image](https://user-images.githubusercontent.com/5960864/47265461-bbd6f580-d55a-11e8-898a-e6fe0838209e.png)

**Comment by yunuo-tech** [comment]
经检查，因为在 android studio3.1下，老是提示替换compile 。
所以我就把`compile project(':jshare-react-native')` 改成了`implementation project(':jshare-react-native')`，然后此问题就出现了，然而别的包没事啊

**Comment by JoshLipan** [comment]
implementation 改成 api 试试
