### ISSUE TITLE
安卓的配置问题

### ISSUE THREAD

**Issue by lhh-sofy** [jpush/jshare-react-native#104]
如图，这些东西需要配置么？请问有什么作用。。。
<img width="815" alt="36517793-70f6-41c0-986e-adf0bdb9e26b" src="https://user-images.githubusercontent.com/13582183/47335919-1a69b400-d6c0-11e8-819c-3434825fbd69.png">

**Comment by JoshLipan** [comment]
这是配置应用签名的，正式发布的时候需要
