### ISSUE TITLE
新浪微博安卓分享图片失败

### ISSUE THREAD

**Issue by lhh-sofy** [jpush/jshare-react-native#107]
截图如下
![image](https://user-images.githubusercontent.com/13582183/48176579-b3006500-e34b-11e8-8614-51737c4f7333.png)

**Comment by JoshLipan** [comment]
新浪微博不支持网络图片分享，只支持本地图片imagePath，参照[极光SDK文档](https://docs.jiguang.cn/jshare/client/Android/android_api/#_39)对照使用
