### ISSUE TITLE
ios分享link问题

### ISSUE THREAD

**Issue by lhh-sofy** [jpush/jshare-react-native#109]
react-native：0.57.3
jshare-react-native:1.3.10
分享数据如下：
`{ type: 'link',
  platform: 'wechat_timeLine',
  text: '看好自己的门，走好自己的路，做好自己的事',
  imageUrl: 'http://p1.pstatp.com/list/pgc-image/1525188721487e8ad97afc2',
  title: '看好自己的门，走好自己的路，做好自己的事',
  url: 'http://nwi.kniel.ssddgg.top./iOlhkvIyNISTsxJBMpXXH27d3RcH2GEb/Vp96aHun-4488635-0' }`
错误返回如下：
`{ description: { error_message: '未完成初始化。' }, code: 40010 }`

**Comment by huangminlinux** [comment]
#110
