### ISSUE TITLE
qq 授权登陆、分享崩溃 微信可以

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#113]
![image](https://user-images.githubusercontent.com/13778798/49271705-c4034880-f4a9-11e8-9050-d7c7358f2b7c.png)

qq 授权登陆、分享崩溃 微信可以

android 8.0 华为荣耀6

**Comment by JoshLipan** [comment]
更新至[v1.4.0](https://github.com/jpush/jshare-react-native/releases/tag/1.4.0)
