### ISSUE TITLE
微信支付回调和分享回调冲突了，怎么办

### ISSUE THREAD

**Issue by TestsLing** [jpush/jshare-react-native#127]
我的这个里面放的是微信支付回调
![image](https://user-images.githubusercontent.com/40593646/61798549-0e33a280-ae5c-11e9-847b-2ff446d138d8.png)

然后我自己创建了另一个 照样继承 但是回调失败 希望有人回应一下
![image](https://user-images.githubusercontent.com/40593646/61798617-2f948e80-ae5c-11e9-88e2-1837e8bf624a.png)

**Comment by TestsLing** [comment]
![image](https://user-images.githubusercontent.com/40593646/61798795-88fcbd80-ae5c-11e9-8b2c-f62dec8663b2.png)
manifest文件指向了那个 但是回调就是失败了  不能正常返回App   分享QQ和微博可以

**Comment by weiruiyang** [comment]
<activity
			android:name=".wxapi.WXEntryActivity"
			 android:theme="@android:style/Theme.Translucent.NoTitleBar"
			android:exported="true" />

这个名字不能变的。
