### ISSUE TITLE
imagePath本地图片路径问题

### ISSUE THREAD

**Issue by huangxiaohao** [jpush/jshare-react-native#14]
您好，我使用jshare进行微信／微博分享，目前遇到的一个问题就是如何设置imagePath本地图片路径？
我按照文档上面的demo方法，但是方法并没有调用。

官方demo上面是这样写的：
```
componentWillMount() {
    NativeAppEventEmitter.addListener('finishGetResource', (result) => {
        this.setState({ 
            imagePath: result.imagePath ,
            videoPath: result.videoPath,
            emotionPath: result.emotionPath,
          });
          console.log(this.state)
        });
  }
```

但是按照这个写法，监听事件并没有被调用，请问这是为什么呢？谢谢！

**Comment by huangxiaohao** [comment]
因为我目前是想分享出去一个链接，这个分享的链接上面会有一个图标。类似我们点完外卖分享出去的链接，上面的那个icon图标。

**Comment by huangminlinux** [comment]
可以参考 demo onShareLinkPress 方法，设置 imagePath 参数。

**Comment by huangxiaohao** [comment]
@huangminlinux 感谢回复  我看的就是这个[https://github.com/jpush/jshare-react-native/blob/master/example/react-native-ios/main_activity.js#L249](https://github.com/jpush/jshare-react-native/blob/master/example/react-native-ios/main_activity.js#L249)

用的就是这个方法：
```
componentWillMount() {
    NativeAppEventEmitter.addListener('finishGetResource', (result) => {
        this.setState({ 
            imagePath: result.imagePath ,
            videoPath: result.videoPath,
            emotionPath: result.emotionPath,
          });
          console.log(this.state)
        });
  }
```

```
var shareParam = {
      platform: "wechat_session",
      type: "link",
      url: "JShare test text",
      imagePath: "",
      imageUrl: "",
      title: " shared link",
      text: "the web link",
    };
    shareParam.imagePath = this.state.imagePath
```

但是我发现这个NativeAppEventEmitter.addListener方法没有被执行，所以我不知道错在哪里了。

**Comment by huangminlinux** [comment]
估计是 native 事件发送太早了，js 监听在事件之后才执行。这个方法和插件本身关系不大，只是为了获得本地图片路径，你那边可以传自己的本地路径。

imagePath 的路径格式可以参考一下： /var/containers/Bundle/Application/1A3B20CA-694F-4305-8C3E-3EB43FA52CE7/jshare.app/wechat@3x.png 

demo 问题我试着调整事件触发时间，你可以更新一下代码看还有没有问题，这边测试是 ok 的

**Comment by huangxiaohao** [comment]
@huangminlinux 您好，我按照您说的方法用react-native-fs获取到了app的绝对路径

> "/var/containers/Bundle/Application/51B6BD23-DACE-42AD-8EA4-F19ED369C36D/YtApp.app/Logo.png"

并且将路径如下拼接：
```
var shareParam = {
                    type: "link",
                    platform: "wechat_session",
                    url: this.state.inviteUrl,
                    imageUrl: RNFS.MainBundlePath+"/Logo.png",
                    title: "******",
                    text: "******"
                };
```

但是分享出来的link还是没有图片，请问是我的路径写错了吗？

**Comment by huangxiaohao** [comment]
按照作者的方法，获取绝对路径可以解决该问题。为作者耐心解答点个赞。。。
感谢。

**Comment by happyxlq** [comment]
import RNFS from 'react-native-fs';

RNFS.stat(image).then((e)=>{
  let message = {
    type: 'link',
   platform: 'wechat_timeLine',  
  url:'',
 imagePath:e.originalFilepath,
 title: '我是title'
 text: 'texxt'
   }
JShareModule.share(message, ()=>{}, ()=>{});
})

路径用originalFilepath 是可以的，大概类似： "/data/user/0/com.xx.xxx"

**Comment by happyxlq** [comment]
完整代码，用react-native 自带的 ImageEditor缩小了图片



                                    JShareModule.isWeChatInstalled((e)=>{
                                        if(e == false)
                                        {
                                            Toast.fail('请安装微信');
                                            return;
                                        }

                                        let cropData = {
                                            offset: {x: 0, y: 0},
                                            size: {width: 120, height: 120},
                                            resizeMode: 'cover',
                                        };
                                        ImageEditor.cropImage(this.state.image , cropData, (image => {

                                            RNFS.stat(image).then((e)=>{console.info(e)
                                                let message = {
                                                    type: 'link',
                                                    platform: 'wechat_timeLine',  // 分享到指定平台，目前只支持趣聊

                                                    url: 'https://www.baidu.com/',
                                                    imagePath:e.originalFilepath,
                                                    title: this.state.title?this.state.title:'',
                                                    text: this.state.content?this.state.content:'',
                                                }

                                                JShareModule.share(message, (map) => {
                                                    console.log("share succeed, map: " + map);
                                                    RNFS.unlink(image)
                                                        .then(() => {
                                                            console.log('FILE DELETED');
                                                        })
                                                        // `unlink` will throw an error, if the item to unlink does not exist
                                                        .catch((err) => {
                                                            console.log(err.message);
                                                        });

                                                }, (map) => {
                                                    RNFS.unlink(image)
                                                        .then(() => {
                                                            console.log('FILE DELETED');
                                                        })
                                                        // `unlink` will throw an error, if the item to unlink does not exist
                                                        .catch((err) => {
                                                            console.log(err.message);
                                                        });
                                                    console.log("share fail, map: ");
                                                    console.info(map);
                                                    Toast.fail('分享失败');
                                                })

                                            }).catch((e)=>{console.info(e)})

                                        }),(e)=>{
                                            console.info(e);
                                        });

                                    })
