### ISSUE TITLE
Project with path ':jcore-react-native' could not be found in project ':app'.

### ISSUE THREAD

**Issue by tea8023sky** [jpush/jshare-react-native#17]
我按照README在android/app/build.gradle文件中添加以下代码
`dependencies {
    compile project(':jshare-react-native') // 不知道这样写   路径对不对
    compile project(':jcore-react-native') // // 不知道这样写   路径对不对
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}`
是不是哪里出错了，请指教。

**Comment by KenChoi1992** [comment]
@tea8023sky settings.gradle 没有配置。
