### ISSUE TITLE
反映一些看文档中发现的一些小瑕疵

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#20]
ios文档

![image](https://user-images.githubusercontent.com/13778798/33201880-4a8281da-d135-11e7-81f8-c2fe771e10c8.png)
1，这一步可以不用了，下载插件下来自动配置了。
![image](https://user-images.githubusercontent.com/13778798/33202061-f5a69b1e-d135-11e7-99ca-c94ff3abf45d.png)
2，这里文档中少了一个空格

**Comment by huangminlinux** [comment]
感谢指正🤝

**Comment by giantss** [comment]
嗯 我们新项目打算 用你们推送、第三方登陆和分享、统计、可能还会用及时通信，这些react native是不是都支持了啊

**Comment by huangminlinux** [comment]
都支持了

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33228432-7dc6a0c8-d1f6-11e7-8018-5b7e64c32c12.png)

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33228409-c8fe3066-d1f5-11e7-9bab-149830998faf.png)

**Comment by KenChoi1992** [comment]
@giantss JPushModule 应该改成 JShareModule

**Comment by KenChoi1992** [comment]
@giantss 更新了版本，修复了这个问题。
