### ISSUE TITLE
ios 中调用JShareModule.authorize

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#23]
![5db1814ae5522eef238f7807954cd005](https://user-images.githubusercontent.com/13778798/33206730-29ed58d0-d146-11e7-97ba-16fdf7de8562.png)

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33228409-c8fe3066-d1f5-11e7-9bab-149830998faf.png)

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33228428-6eb79466-d1f6-11e7-90b4-1071fa8a702f.png)

**Comment by KenChoi1992** [comment]
@giantss 更新了文档，iOS 没有这个方法。

**Comment by giantss** [comment]
@KenChoi1992 ios没有这个方法 那第三方授权是怎么做。。。
