### ISSUE TITLE
关于android配置的一些疑问

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#24]
![image](https://user-images.githubusercontent.com/13778798/33207569-28d4cdea-d149-11e7-8cde-be2c6de2ab9e.png)

**Comment by KenChoi1992** [comment]
@giantss 看看文档啊，JSHARE_PKGNAME 和 applicationId 一样的。如果你不看文档，你参考 demo 的 build.gradle 也行。

**Comment by giantss** [comment]
我看了 ，demo我没运行起来 所以提了这个问题
