### ISSUE TITLE
android中调用JShareModule.setDebug({enable: true});报错

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#25]
![image](https://user-images.githubusercontent.com/13778798/33226361-053b5196-d1c7-11e7-828e-82ae4a6519cd.png)
![e64cf67c0bf789f176bfff3b63119a26](https://user-images.githubusercontent.com/13778798/33226376-2490b5d6-d1c7-11e7-90ca-6be97cdea04e.jpg)

**Comment by KenChoi1992** [comment]
@giantss 看下 demo 的 MainApplication

**Comment by giantss** [comment]
@KenChoi1992 你的意思是这个api是在MainApplication里面调用吗
![image](https://user-images.githubusercontent.com/13778798/33248397-b7fad3da-d35f-11e7-8f72-97debabe61ae.png)

**Comment by KenChoi1992** [comment]
@giantss Android 的话最好在这里调，而不是在 JS 中调用。1.1.1 中也添加了这个方法，JS 中调用也不会出错了。
