### ISSUE TITLE
android平台调用authorize返回  errorCode 40012

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#27]
![image](https://user-images.githubusercontent.com/13778798/33226559-dac65ba4-d1cb-11e7-97b3-248a494bed9d.png)

![image](https://user-images.githubusercontent.com/13778798/33226551-9cb4c968-d1cb-11e7-9648-d432e293f45d.png)
![image](https://user-images.githubusercontent.com/13778798/33226553-aba377f8-d1cb-11e7-90bc-8e8d9dc00266.png)
有点看不懂了

**Comment by KenChoi1992** [comment]
@giantss 有没有按照文档配置好？https://github.com/jpush/jshare-react-native/blob/master/docs/JGShareSDK.md

**Comment by giantss** [comment]
配置了 
![image](https://user-images.githubusercontent.com/13778798/33247923-a8715acc-d35c-11e7-864f-e7a784b1f9d1.png)
里面的信息都换成自己的了

**Comment by KenChoi1992** [comment]
@giantss 这个问题还没有解决吗？

**Comment by giantss** [comment]
先关闭吧 新项目中还没使用过
