### ISSUE TITLE
example ios android都不能运行

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#28]
我的操作步骤
1，clone
2，cd example/
3，npm install
4，react-native run-android/run-ios
都是编译失败

![image](https://user-images.githubusercontent.com/13778798/33226859-8da6fa1c-d1d1-11e7-8dd8-ca4532d1e7a4.png)
![image](https://user-images.githubusercontent.com/13778798/33226869-a4dba62e-d1d1-11e7-97d3-3de348070025.png)

**Comment by KenChoi1992** [comment]
@giantss 可能因为 RN 的脚本找不到 AndroidManifest，我运行一般都是先 npm start，然后再用 AS 运行项目。

**Comment by KenChoi1992** [comment]
我在 dev 分支下改了项目结构，你再试试看

**Comment by giantss** [comment]
@KenChoi1992 嗯 好的

**Comment by giantss** [comment]
还是build失败

**Comment by KenChoi1992** [comment]
@giantss 报什么错？

**Comment by giantss** [comment]
不纠结这个demo了 我自己写了一个demo，可以浏览推送、授权登陆、分享、统计。看这里https://github.com/giantss/DemoApp/
