### ISSUE TITLE
ios分享接口问题

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#29]
ios所有分享
![image](https://user-images.githubusercontent.com/13778798/33228581-c80e71da-d1f9-11e7-8ce7-8dfab03b2f15.png)

**Comment by giantss** [comment]
![image](https://user-images.githubusercontent.com/13778798/33229075-caa59bd6-d202-11e7-9b08-c58c534a92cd.png)
ios图片分享报了错`share failed, map: {"code":41014,"description":"Error Domain=JShareErrorDomain Code=41014 \"(null)\" UserInfo={error_message=The mediaType is JSHAREImage,this JSHAREMessage instance's image can't be nil!}"}` 查了错误代码，说`图像是空的`，但我图像链接已经给了，同样的图片配置分享链接是可以分享成功的

**Comment by huangminlinux** [comment]
iOS 不支持这个字段， imageUrl 只能使用 本地图片路径。

**Comment by giantss** [comment]
@huangminlinux  
![image](https://user-images.githubusercontent.com/13778798/33248280-22663ada-d35f-11e7-8ae2-43bf92d43063.png)
这是你们的注释啊 
imageUrl是网络图片
imagePath才是本地图片

**Comment by huangminlinux** [comment]
图片 URL 只有 android 端才支持，
![image](https://user-images.githubusercontent.com/5852088/33248514-5548b756-d360-11e7-8a0c-73e383a54c2b.png)

demo 注释还没更新回头更新一下。
