### ISSUE TITLE
微信朋友圈分享没有图

### ISSUE THREAD

**Issue by kala888** [jpush/jshare-react-native#33]
"jshare-react-native": "^1.1.2",

 share = () => {
    const shareParam = {
      platform: "wechat_timeLine",
      type: "link",
      url: "JShare test text",
      imagePath: "",
      title: "前律师谈朴槿惠：她腰不好常喊疼 狱中仍操心国事",
      text: "外网12月6日电自从10月中旬7名辩护律师集体辞职后，朴槿惠一直闭门不出、拒绝出庭，引发舆论持续关注。近日，其前任律师都泰宇接受韩媒channel A《局外人》节目采访时，介绍了朴槿惠的近况",
      imageUrl: "http://bbt-test.oss-cn-shanghai.aliyuncs.com/images/CU000401/2017/0926/110549_6311318.jpg?x-oss-process=style/normal"
    }

![image](https://user-images.githubusercontent.com/1215976/33649390-c0ec337c-da98-11e7-9156-beb43a292abb.png)

**Comment by kala888** [comment]
临时解决方案，下载图片到缓存中使用imagePath替换imageURL
`    RNFetchBlob.config({ fileCache: true })
      .fetch('GET', shareParam.imageUrl, {})
      .then(res => {
        shareParam.imageUrl = ''
        shareParam.imagePath = res.path()

        JShareModule.share(
          shareParam,
          map => {
            this.showTips(JSON.stringify(map))
          },
          map => {
            this.showTips(JSON.stringify(map))
          }
        )
      })
`

**Comment by KenChoi1992** [comment]
换成本地图片试试？

**Comment by readthecodes** [comment]
网络图片地址是最常用的，希望能支持一下！在RN里面本地图片绝对路径怎么找？

**Comment by KenChoi1992** [comment]
@readthecodes https://docs.jiguang.cn/jshare/client/Android/android_api/#_24 我们的 SDK 不支持微信分享网络图片。有的平台支持，具体可以参考文档。RN 里面图片你可以存储到自己的应用下，也可以存到 sdcard 里。网络上有很多资料。
