### ISSUE TITLE
微信登录时报错：iOS错误代码：42001；android错误代码：invalid appsecret

### ISSUE THREAD

**Issue by pampang** [jpush/jshare-react-native#34]
iOS:
```
"Error Domain=JShareErrorDomain_weChat Code=42001 "未能完成操作。（“JShareErrorDomain_weChat”错误 42001。）" UserInfo=0x175073f40 {error_message=invalid credential, access_token is invalid or not latest, hints: [ req_id: 0a.cNa0494s152 ]}"
```

android: 
```
java.lang.Throwable: invalid appsecret, view more at http://t.cn/RAEkdVq, hints: [ req_id: hI0889th36 ]
 at cn.jiguang.share.android.api.AbsPlatform.notifyError(Unknown Source)
 at cn.jiguang.share.wechat.d.run(Unknown Source)
```

P.S.: 似乎在android下，报上述错误的时候，不会进入到 onError 中。

实在抱歉通过这种形式来问问题，但问题没有解决思路，而项目急需上线，烦请多多见谅。如果有解决方案，感谢你留下你的做法~

**Comment by pampang** [comment]
iOS 调用的是 JShareModule.getSocialUserInfo
android 调用的是 JShareModule.authorize。
都可以进入到微信的授权登录页面，完成授权之后，返回到APP，就会显示上述错误。

**Comment by huangminlinux** [comment]
setup config 参数方法中的 wechatAppSecret 字段有问题。

**Comment by pampang** [comment]
是指我的微信appSecret不对吗？因为微信的appSecret是无法再次获取到的，只能重置，我非常担心重置之后会造成什么不良的影响

**Comment by huangminlinux** [comment]
看这错误是 appSecret 没有填写正确。

**Comment by pampang** [comment]
iOS 上的报错，说的是 access_token 不正确，请问这个也是由于 appSecret 不对，导致获取了一个错误的 access_token 所导致的？

**Comment by pampang** [comment]
请问您能加一下我的微信或者QQ吗：393390587，我们很希望能够在今天之内把分享、登录给对接成功。感激不尽

**Comment by huangminlinux** [comment]
都是一个问题，只是错误描述不一样。

**Comment by pampang** [comment]
重置 appSecret 之后，问题解决了。应该是因为 appSecret 不正确导致的问题。

**Comment by panhs** [comment]
不重置解决不了吗  因为我们app已经上线了 不能随便改微信的appSecret 改了之前上线的分享就用不了了。
