### ISSUE TITLE
error undefined is not an object

### ISSUE THREAD

**Issue by panhs** [jpush/jshare-react-native#38]
undefined is not an object (evaluating 'JShareModule.getPlatformList') - --  -- -
问题解决了   是link的问题
配置完了 获取分享的平台列表是空的  是什么原因

**Comment by KenChoi1992** [comment]
@panhs JGShareSDK.xml 配置了吗

**Comment by KenChoi1992** [comment]
@panhs 没有回复就先关闭了。
