### ISSUE TITLE
jshare-react-native是否已经可以使用？

### ISSUE THREAD

**Issue by dx51job** [jpush/jshare-react-native#4]
你好，请问jshare-react-native目前是否可以使用？支持哪些分享平台？谢谢！

**Comment by huangminlinux** [comment]
可以使用了，可以运行 demo 看看效果。

**Comment by dx51job** [comment]
@huangminlinux 
 jshare-react-native/android/src/main/java/cn/jiguang/share/reactnative/JShareModule.java 
友情提示，284行应该是getGender()，拼错了哦…

**Comment by KenChoi1992** [comment]
@dx51job SDK 的接口给错了啊……已经反馈了

**Comment by huangminlinux** [comment]
@dx51job  感谢提醒

**Comment by dx51job** [comment]
求助，组件没有尝试成功。
1. Get Platform List点击没有反应，adb log也没有打印。
查看了一下JShareModule.java的代码，
Android Studio提示“Method 'getPlatformList(com.facebook.react.bridge.Callback)' is never used”

2. Get userInfo，log打印fail 。
08-03 17:01:54.789: E/JIGUANG-JShare(21248): [JShareInterface] do fail, can not find Wechat platform.
08-03 17:01:54.789: W/System.err(21248): 	at cn.jiguang.share.android.api.JShareInterface.checkArgs(Unknown Source)
08-03 17:01:54.789: W/System.err(21248): 	at cn.jiguang.share.android.api.JShareInterface.getUserInfo(Unknown Source)
08-03 17:01:54.789: W/System.err(21248): 	at cn.jiguang.share.reactnative.JShareModule.getSocialUserInfo(JShareModule.java:274)

**Comment by KenChoi1992** [comment]
@dx51job 除了配置 JGShareSDK.xml 其他的也要配置，有没有 JCore 版本号打印，如果没有那就可能没有配置成功，另外 AS 那个提示不用管。

**Comment by dx51job** [comment]
@KenChoi1992 你好，我又反复重新试了几次，还是一样的log打印。debug版本和release版本试下来都一样。
我是照着github上的说明一步一步配置的，JGShareSDK.xml也配置好（里面目前只配置了微信的）放到assets目录里了。。

JCore版本号打印好像没有看到，版本号打印的log可否给个例子，我再确认一下，谢谢！

**Comment by KenChoi1992** [comment]
@dx51job 
![image](https://user-images.githubusercontent.com/8196928/29059510-6ede3084-7c48-11e7-807c-f67b5036aac1.png)
这是我的日志打印，另外点击 Get Platform List 会打印：
```
ReactNativeJS: list: Wechat,WechatMoments,WechatFavorite,QQ,QZone,SinaWeibo,SinaWeiboMessage
```

**Comment by lhhhhhhhhh** [comment]
请问下，分享弹出的qq、微信...的那些logo列表是自己去弄的么？

**Comment by huangminlinux** [comment]
qq、微信 。。。 分享要去对应的开发者平台注册你的应用，然后替换 对应 appkey。

**Comment by lhhhhhhhhh** [comment]
请问下，分享图片，提示分享成功（在qq界面显示的），但是图片没发成功，有个红色的感叹号是怎么回事？而且share方法没返回任何东西。求大神们指点，感谢
![screenshot_2017-09-22-16-29-58-287_com tencent mo](https://user-images.githubusercontent.com/32149773/30736037-d6f69894-9fb3-11e7-8b43-942122dffebd.png)

**Comment by huangminlinux** [comment]
没有回调问题：
Appdelegate.m 的代码添加了吗
 https://github.com/jpush/jshare-react-native/blob/master/docs/iOSConfig.md

发送错误要看具体的错误原因

**Comment by lhhhhhhhhh** [comment]
@huangminlinux  你好，我是开发android出现的这个问题。

**Comment by KenChoi1992** [comment]
@lhhhhhhhhh 看下日志

**Comment by lhhhhhhhhh** [comment]
@huangminlinux 请问下  有没有对应的errorCode表？  获取用户信息的方法getSocialUserInfo返回了errorCode:-6（分享platform：wechat_session）。

**Comment by giantss** [comment]
Get Platform List点击没有反应，adb log打印list为空。
08-03 18:14:47.513: I/ReactNativeJS(28464): list:
查看了一下JShareModule.java的代码，
Android Studio提示“Method 'getPlatformList(com.facebook.react.bridge.Callback)' is never used”

Get userInfo，log打印errorCode: 40012，platform 没配置
08-03 17:01:54.789: E/JIGUANG-JShare(21248): [JShareInterface] do fail, can not find Wechat platform.
08-03 17:01:54.789: W/System.err(21248): at cn.jiguang.share.android.api.JShareInterface.checkArgs(Unknown Source)
08-03 17:01:54.789: W/System.err(21248): at cn.jiguang.share.android.api.JShareInterface.getUserInfo(Unknown Source)
08-03 17:01:54.789: W/System.err(21248): at cn.jiguang.share.reactnative.JShareModule.getSocialUserInfo(JShareModule.java:274)

@KenChoi1992 @huangminlinux  我也出现了这个问题，一摸一样的。都是按照文档配置的 不知道哪里出了问题。（弱弱的问一句：android这项配置https://github.com/jpush/jshare-react-native/blob/master/docs/JGShareSDK.md 在代码中哪里读取的？Get Platform List 打印空，是否跟这个配置项没有读取到有关呢？）

**Comment by KenChoi1992** [comment]
这个提示“Method 'getPlatformList(com.facebook.react.bridge.Callback)' is never used” 是在 Java 中没直接调用会报，但这个接口其实是 JS 中调用的。所以不用管。领完 JGShareSDK.xml 是 jshare sdk 中读取的。

**Comment by giantss** [comment]
@KenChoi1992 我在js中调用
![image](https://user-images.githubusercontent.com/13778798/33249081-64fd7620-d363-11e7-897e-34cb0cf6c4c7.png)
返回的是空
![image](https://user-images.githubusercontent.com/13778798/33249091-7a9d44f6-d363-11e7-8797-ebdce64d31aa.png)
这是什么原因呢

**Comment by KenChoi1992** [comment]
@giantss 过滤一下日志，关键字 JCore，看看 init 成功没有

**Comment by giantss** [comment]
@KenChoi1992 
![image](https://user-images.githubusercontent.com/13778798/33249654-c7ac064e-d366-11e7-876a-bafd79e88083.png)
