### ISSUE TITLE
仔细测试过分享得出的结论

### ISSUE THREAD

**Issue by giantss** [jpush/jshare-react-native#50]
jshare-react-native 1.1.7
以下测试数据平均每个分享3次测试，取消分享回调测试和分享回调测试
## Ios取消分享回调和分享回调结果：
![image](https://user-images.githubusercontent.com/13778798/35150185-500bc42c-fd54-11e7-828e-c235d92d7d0a.png)
## android取消分享回调和分享回调结果：
![image](https://user-images.githubusercontent.com/13778798/35150274-c32bb6a6-fd54-11e7-990c-7dd74b95ee96.png)
综上测试提出几点建议：
1，统一ios、android回调参数格式，今天在群里提过了，但是貌似没有完全统一，这对于使用者（特别像我这种有代码强迫症的猿）来说使用起来非常的不友好。
类似：
```
{
	“code”: “正确／错误代码”，
	“message”: “正确／错误代码的解释”,
	“platform”：“分享平台的名称”
}
```
2，(看图中标记)android 上问题感觉比较多，有的时候回调有的时候不回调，没有规律，不知道什么情况，麻烦发布版本的时候测试以下啊 😂。
3，首先非常感谢你们提供给各类插件，但是如果在我们集成使用阶段花费我们太多的时间的话，对开发进度造成了影响，结果是糟糕的。
4，最后麻烦你们尽快修复，项目月底要上线，比较赶啊。。。
@KenChoi1992 @huangminlinux

**Comment by huangminlinux** [comment]
可以升级到 [1.1.8 版本](https://github.com/jpush/jshare-react-native/releases/tag/1.1.8)。

**Comment by giantss** [comment]
ok
