### ISSUE TITLE
调用微信

### ISSUE THREAD

**Issue by tianweicc** [jpush/jshare-react-native#54]
弹出吐司说正在打开  然后就没反应了 是签名的问题？

**Comment by huangminlinux** [comment]
iOS 还是 android ？

**Comment by tianweicc** [comment]
@huangminlinux  android  然后

 var message = {
      platform: "wechat_timeLine",
      type: "text",
      text: "JShare test text",
    };
    JShareModule.share(message, (map) => {
      console.log("share succeed, map: " + map);
    }, (map) => {
      console.log("share failed, map: " + map);
    })

使用这个 会出现上述问题

**Comment by tianweicc** [comment]
@huangminlinux 
![8de211575824f3656428752fd1d927c7](https://user-images.githubusercontent.com/17263719/36766876-bf45f500-1c72-11e8-9093-1219f7a14493.jpg)
测试别的方法  授权有问题

**Comment by KenChoi1992** [comment]
@tianweicc 这样写
```
console.log("errorCode " + JSON.stringify(error));
```
看看是什么 code

**Comment by tianweicc** [comment]
![1328daf08407f8a8ff0a2e8c0f004cea](https://user-images.githubusercontent.com/17263719/36767119-11cdeef8-1c74-11e8-93fd-b1a651de6b0a.jpg)
@KenChoi1992

**Comment by KenChoi1992** [comment]
@tianweicc 看日志是你没配置好

**Comment by tianweicc** [comment]
@KenChoi1992  打包测试 文字 url 都可以成功分享 图片  配置始终不成功， 必须本地路径么？ 使用网络路径 调用微信的时候  报错信息是  code：41014 description：图片参数为空
![58e06ac51a7156d07eab9c281cd000c4](https://user-images.githubusercontent.com/17263719/36771067-147659dc-1c89-11e8-8182-9f32e70b08ec.jpg)

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/36771268-56f2312c-1c8a-11e8-864d-70d032df6f44.png)
麻烦调用每个接口前看下 index.js 相关的注释

**Comment by tianweicc** [comment]
大佬。。。我这个图只是为了方便你看  我使用的时候 只使用了imageUrl 然后放网络图 是报这个错。。

**Comment by tianweicc** [comment]
@KenChoi1992 
![1](https://user-images.githubusercontent.com/17263719/36772836-c0f21fea-1c91-11e8-9872-ef0c5efc099f.jpg)
![2](https://user-images.githubusercontent.com/17263719/36772838-c21abc60-1c91-11e8-8707-44d46c9b6e29.jpg)
分别尝试了第一种 跟第二种。。 都是拿不到资源信息， 本地路径的那个可能是我这边路径给错了  网络资源是拿不到。

**Comment by KenChoi1992** [comment]
@tianweicc 你可以看看 https://docs.jiguang.cn/jshare/client/Android/android_api/#_37 文档，有些平台不支持网络图片，比如微信。

**Comment by KenChoi1992** [comment]
imagePath 去掉 file:// 前缀。可以参考 example 的代码。

**Comment by tianweicc** [comment]
@KenChoi1992 本地的我这边ok了   使用wechat可以分享网络图片  是你们极光这边的不支持网络图是么？

**Comment by KenChoi1992** [comment]
@tianweicc qq 可以，微信不行

**Comment by tianweicc** [comment]
谢谢了

**Comment by tianweicc** [comment]
还有一个问题 各位大佬  极光有提供微信登录 qq登录 微博登录  这种第三方登录么、。？

**Comment by huangminlinux** [comment]
参考 authorize 方法。

**Comment by tianweicc** [comment]
@KenChoi1992 @huangminlinux  本地路径图片 去掉file:// 前缀 还是不行  现在的图片路径是
 'data/user/0/com.cnabs.debug/cache/ReactNative-snapshot-image1571374826.jpg'

**Comment by KenChoi1992** [comment]
我叫你去掉file:// 前缀，你为什么又要弄成 data/user/0/ 呢？只要后面的就行了
![image](https://user-images.githubusercontent.com/8196928/36838112-3c3511e8-1d79-11e8-9f85-600073ec2699.png)

**Comment by tianweicc** [comment]
![Uploading 5FBFA1A34A246E783E571734DC5EF404.jpg…]()
图片路径对了 本地 是按照你说的  然后分享会挂掉  说key不对  重新对了一遍引入分享的流程  没有发现问题  分享文字成功 ios分享图片成功  android报错

**Comment by tianweicc** [comment]
debug跟随  没发现错误 还是报key的问题 
![Uploading 111111.jpg…]()

**Comment by KenChoi1992** [comment]
提供一下完整的报错日志

**Comment by tianweicc** [comment]
![3d749961e862cc08122d88e460d3a0e1](https://user-images.githubusercontent.com/17263719/36882701-6120ec6a-1e10-11e8-8232-64426cc113e1.jpg)
@

**Comment by tianweicc** [comment]
@huangminlinux 测试  网页 文字 都可以  现在就是图片 报错

**Comment by KenChoi1992** [comment]
![image](https://user-images.githubusercontent.com/8196928/36887740-79a33064-1e2d-11e8-9046-623f3912090d.png)
你的参数没有 text 字段。

**Comment by tianweicc** [comment]
![333](https://user-images.githubusercontent.com/17263719/36887850-f1e237f0-1e2d-11e8-8559-2a076144115c.jpg)
这个字段？  不是选填么？

**Comment by KenChoi1992** [comment]
更新一下 1.2.0
