### ISSUE TITLE
iOS安装编译报错

### ISSUE THREAD

**Issue by Lxxyx** [jpush/jshare-react-native#56]
背景：纯RN项目

1. 安装
2. react-native link

Headers search path已加

编译时报错：

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_JSHAREService", referenced from:
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64

另外在使用 pods install 添加依赖时，Pods会安装 React 的依赖

**Comment by huangminlinux** [comment]
检查配置项加了没 https://github.com/jpush/jshare-react-native/blob/master/docs/iOSConfig.md#添加搜索路径

**Comment by Lxxyx** [comment]
确定是已添加了的。上面也提过 Headers search path已加

**Comment by Lxxyx** [comment]
![image](https://user-images.githubusercontent.com/13161470/36856138-3c928878-1db0-11e8-960a-3cd8f3e27ac9.png)

**Comment by Lxxyx** [comment]
![image](https://user-images.githubusercontent.com/13161470/36856276-929102ae-1db0-11e8-855a-6bf297a6b735.png)

**Comment by huangminlinux** [comment]
编译选项是否设为 release 了？

**Comment by huangminlinux** [comment]
换成真机看看还有没问题。

**Comment by Lxxyx** [comment]
设为 release 一样报错

![image](https://user-images.githubusercontent.com/13161470/36881834-4f276494-1e0b-11e8-8dd1-95a583c194c7.png)

**Comment by Lxxyx** [comment]
真机装不上。打包时候就报错了，archive无法生成安装包

**Comment by Lxxyx** [comment]
因为 link 失败出现的问题。
需要用户手动链接文件：

1. 找到node_modules/jshare-react-native
2. 
![image](https://user-images.githubusercontent.com/13161470/36882282-e1c1aef2-1e0d-11e8-89cc-6772b0936acb.png)
3. 拖到
![image](https://user-images.githubusercontent.com/13161470/36882291-ed00f4b2-1e0d-11e8-8c7e-de0f45dc389a.png)
下
4. 
![image](https://user-images.githubusercontent.com/13161470/36882302-f8e20a96-1e0d-11e8-83fd-3ea2c303eb43.png)

模拟器有错误的参考这个：https://github.com/jpush/jpush-react-native/issues/104#issuecomment-269127564

谢谢 @huangminlinux 的热心解答
