### ISSUE TITLE
为什么 IOS 还要设置JShareModule.setup()，不安全

### ISSUE THREAD

**Issue by yunuo-tech** [jpush/jshare-react-native#58]
JShareModule.setup() 这个设置方法为什么要在 js 中实现，直接在原生中设置下不更好吗

现在解压安装包 打开main.jsbundle 就能直接看到各个平台的密匙了

**Comment by huangminlinux** [comment]
下个版本放到原生配置中。

**Comment by huangminlinux** [comment]
可以使用 [jshare-react-native@1.3.0](https://github.com/jpush/jshare-react-native/releases/tag/1.3.0) 版本。
