### ISSUE TITLE
【iOS】集成报错: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by huangxiaohao** [jpush/jshare-react-native#6]
作者您好，按照步骤集成了您的组件，但是出现如下报错，导致方法调用不到，请问该如何解决，谢谢！

Showing Recent Errors Only:

```
ld: 651 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by huangminlinux** [comment]
代码里面有方法名重复了， 能提供更全的日志信息吗？

**Comment by huangxiaohao** [comment]
您说的是这个吗
![image](https://user-images.githubusercontent.com/13390763/29055050-b2d2a99e-7c2c-11e7-96b7-5a3e07fb8a3d.png)

**Comment by huangxiaohao** [comment]
更新最新版本即可。感谢@huangminlinux
