### ISSUE TITLE
iOS平台 RCTJShareConfig.plist 文件配置无法生效

### ISSUE THREAD

**Issue by lanjiemm** [jpush/jshare-react-native#63]
![image](https://user-images.githubusercontent.com/20971872/37859741-cac31888-2f53-11e8-815d-568afff9b876.png)
![image](https://user-images.githubusercontent.com/20971872/37859748-edd09292-2f53-11e8-8b5e-d34f016126a1.png)
我的rn版本是0.40.0
电脑系统是mac

安卓手机上分享QQ QQ空间都没问题
iOS 手机上分享QQ可以分享, 但是在分享QQ空间的时候
弹框提示分享失败应用不存在

**Comment by huangminlinux** [comment]
手机使用的是什么设备？

使用 demo 是否可以正常分享？
