### ISSUE TITLE
分享失败：未完成初始化

### ISSUE THREAD

**Issue by Riant** [jpush/jshare-react-native#70]
版本信息：
```
    "react-native": "0.54.2",
    "janalytics-react-native": "^1.1.2",
    "jcore-react-native": "^1.2.5",
    "jpush-react-native": "^2.1.13",
    "jshare-react-native": "^1.3.1",
```

使用 `pod install` 安装的。

`RCTJShareConfig.plist` 也已经创建了，并且在 Xcode 中打断点跟进 setup 方法中了，但是在分享的时候，还是返回了 未完成初始化 的错误。

截图如下：

<img width="650" alt="2018-04-23 18 28 00" src="https://user-images.githubusercontent.com/668285/39121873-982f8c00-4725-11e8-9104-90e7bc4d79f1.png">

<img width="573" alt="2018-04-23 18 27 49" src="https://user-images.githubusercontent.com/668285/39121858-845886fa-4725-11e8-80b5-74b62ce95be1.png">

<img width="551" alt="2018-04-23 18 30 27" src="https://user-images.githubusercontent.com/668285/39121889-a28373e2-4725-11e8-9de4-59be877df7bc.png">

谢谢。

另外，我的 iOS 端的统计貌似也是有问题的，极光后台统计数据页面还是提示“您还没有集成极光开发者服务SDK”。

补一个启动之后，XCode输出的日志，极光相关部分的截图
<img width="529" alt="2018-04-24 09 53 05" src="https://user-images.githubusercontent.com/668285/39161957-a94cc16c-47a5-11e8-9f47-806344eb9e9c.png">

**Comment by Riant** [comment]
哦，解决了，JPush 的 `您配置的 AppKey 尚未配置 iOS 平台` 错误导致 JShare, JAnalytics 均不能正常工作。

希望相关文档能够明确说明。

谢谢。

**Comment by 66543210** [comment]
> 哦，解决了，JPush 的 `您配置的 AppKey 尚未配置 iOS 平台` 错误导致 JShare, JAnalytics 均不能正常工作。
> 
> 希望相关文档能够明确说明。
> 
> 谢谢。

然而时至今日还是有这个坑，真的是调了好久+问官方都没解决。感谢楼主分享不然不知道还要调多久
