### ISSUE TITLE
RN 项目集成进去之后报错 40010 未完成初始化

### ISSUE THREAD

**Issue by Z-hy** [jpush/jshare-react-native#76]
按照步骤在iOS 项目里面集成极光分享，但是一直报错未完成初始化，找不到错误在哪里。

**Comment by huangminlinux** [comment]
#41 看看是不是同一个问题。

**Comment by Z-hy** [comment]
谢谢，问题找到了，是RCTJShareConfig.plist 文件有地方没写对。

**Comment by 1103782409qq** [comment]
> 谢谢，问题找到了，是RCTJShareConfig.plist 文件有地方没写对。

代码不需要改吗，我也遇到这个问题，能否加个微信，或者加我的13691711503

**Comment by mrtian** [comment]
2018-11-29 00:48:19.768569+0800 gzhrn[58149:11147511] { description: { error_message: '未完成初始化。' }, code: 40010 }

对照了N次plist ,没发现有问题，也报这个错误呢？

**Comment by xiao-shuai** [comment]
> 谢谢，问题找到了，是RCTJShareConfig.plist 文件有地方没写对。

什么地方 ？我找不到啊
