### ISSUE TITLE
微信分享返回错误码为“-6”，没有描述，该怎么解决？

### ISSUE THREAD

**Issue by zhugy-yami** [jpush/jshare-react-native#79]
微信分享返回的数据：
{"description":"Cannot find the description","state":"fail","code":-6}

**Comment by JoshLipan** [comment]
错误是签名与后台配置不一致，由于微信会有缓存，清除微信缓存后再试下。参照[这个问题](https://community.jiguang.cn/t/eclipse-jshare-null/20140/17)
