### ISSUE TITLE
authorize 在oc中并没有实现，getSocialUserInfo在oc中拼错成了getSoicalUserInfo

### ISSUE THREAD

**Issue by jasonchou3** [jpush/jshare-react-native#8]
以上两个方法无法使用

**Comment by jasonchou3** [comment]
开始尝试修改：
1.直接调用module的getSoicalUserInfo，js无法获得回调。
2.在oc的回调中打log，没有出现log，oc无法获得回调。
3.尝试更新依赖包，share包从1.2.0升级到1.2.1，core包无法得知当前版本（名字上没写囧）直接替换为1.1.5，无效

推测：怀疑原生sdk无法回调？？？

另：分享能够回调

**Comment by jasonchou3** [comment]
问题2：
微信分享回调无论是取消，成功，返回值都为unknown

**Comment by huangminlinux** [comment]
回调问题，需要在 做一些配置，文档没有说清楚，现在已经补上。

### 在 Appdelegate.m 中插入代码

加入头文件 `RCTJShareModule.h`

```objective-c
#import <RCTJShareModule.h>
```

添加 `handleOpenURL`

```objective-c
- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url{
  [JSHAREService handleOpenUrl:url];
  return YES;
}
```

### 添加搜索路径

TARGET -> Build Settings -> Header Search Paths 添加搜索路径

```
$(SRCROOT)/../node_modules/jshare-react-native/ios/RCTJShareModule
```
命名问题下个版本中修复

**Comment by huangminlinux** [comment]
命名问题可以更新到 [1.0.5](https://github.com/jpush/jshare-react-native/releases/tag/1.0.5) 版本

**Comment by JoeyCurry** [comment]
版本号: 1.1.3 命名问题仍然存在，getSocialUserInfo在oc中拼错成了getSoicalUserInfo

**Comment by kala888** [comment]
@JoeyCurry 新的pr修复这个问题，要等新的release

**Comment by huangminlinux** [comment]
@JoeyCurry  @kala888  可以升级到 1.14 版本。
