### ISSUE TITLE
package cn.jiguang.share.wechat does not exist

### ISSUE THREAD

**Issue by mengerzhuanyong** [jpush/jshare-react-native#80]
![image](https://user-images.githubusercontent.com/19523478/41328054-b3eeab6a-6ef8-11e8-9f37-a81f40dd6a40.png)

如图，一直在报这个错误，重新安装之后还是报错，求解答呀！～

**Comment by JoshLipan** [comment]
安装完，按[android配置流程](https://github.com/jpush/jshare-react-native#android)检查你的项目
