### ISSUE TITLE
ios 微信分享后，点击“返回[应用名]” 无法回到app

### ISSUE THREAD

**Issue by wikieswan** [jpush/jshare-react-native#85]
你好，首先感谢 ```jshare-react-native ``` 为我们在rn环境提供分享功能。

## 问题描述：

ios 微信分享后，点击“返回[应用名]” 无法回到app

## 详细步骤：

app 里面点击分享按钮，分享到微信给好友，微信提示“返回[应用名]” 、“留着微信” ，点击这两个选项都是留着微信，而不能返回到 app

## 截图

![image](https://user-images.githubusercontent.com/7147483/42208606-2a778b9e-7edf-11e8-828c-8e9e55890489.png)

## 代码

	constructor(props) {
	    super(props);
	    JShareModule.setup();
	  }

	  shareWx() {
	    JShareModule.isWeChatInstalled((isInstalled) => {
	      console.log('isWeChatInstalled:', isInstalled);
	      if (!isInstalled) return;
	      const message = {
	        type: 'link',
	        platform: 'wechat_session',  // 分享到指定平台
	        url: 'http://h5.shiyanzhushou.com', // 必填，网页 url
	        // imagePath: String // 选填，本地图片路径 imagePath，imageUrl 必须二选一
	        imageUrl: 'https://file.syzsstatic.com/512.png', // 选填，网络图片地址 imagePath imageUrl 必须二选一
	        title: 'share test', // 选填
	        text: 'shiyanzhushou', // 选填
	      };
	      JShareModule.share(message, e => console.log('success', e), f => console.log('fail', f));
	    });
	  }

谢谢

**Comment by huangminlinux** [comment]
检查 AppDelegate.m 添加了代码没
```
// work in iOS(8.0)
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  [JSHAREService handleOpenUrl:url];
  return YES;
}
// work in iOS(9_0)
- (BOOL)application:(UIApplication *)application handleOpenURL:(NSURL *)url{
  [JSHAREService handleOpenUrl:url];
  return YES;
}
// work in iOS(9_0,++)
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  [JSHAREService handleOpenUrl:url];
  return YES;
}
```

**Comment by wikieswan** [comment]
确认这段代码是有的

**Comment by huangminlinux** [comment]
还有就是 URL Types 这个地方是否填写正确， 一般就这两个地方。

**Comment by wikieswan** [comment]
这里是我的 URL 配置

![image](https://user-images.githubusercontent.com/7147483/42212230-1bdb6912-7ee8-11e8-9844-acebce06ed20.png)

QQ 的返回时正确的
微信是不能返回的

我的极光appKey 是`fe70fbxxxxxxxx`,请帮我看下我的配置有什么不对的地方

**Comment by wikieswan** [comment]
请问微信的 URL Schemes 格式是 `wx[jpush appkey]` 吗
如果是的话 我确认上面的截图里面没有拼写的错误

**Comment by huangminlinux** [comment]
微信的 key

**Comment by wikieswan** [comment]
好的 谢谢
