### ISSUE TITLE
TypeError: TypeError: TypeError: undefined is not an object (evaluating 'JShare Module.setup')

### ISSUE THREAD

**Issue by lxnxbnq** [jpush/jshare-react-native#92]
配置好android平台后，报错如标题。
代码:
`
import JShareModule from 'jshare-react-native';

    componentDidMount(){
        JShareModule.setup()
    }

    successCallback(){
        console.log('分享成功')
    }

    failCallback(errorCode){
        console.log('分享失败:',errorCode)
    }

    _shareWeChat = () => {
        const message = {
            type : 'text',
            platformString : 'wechat_session',
            text : '测试分享',
            imagePath : ''
        }
        JShareModule.share(message,this.successCallback,this.failCallback)
    }

`

**Comment by JoshLipan** [comment]
JShareModule.setup() only for Ios.

**Comment by JoshLipan** [comment]
插件没接入成功，根据[Android配置](https://github.com/jpush/jshare-react-native#manually-configure-part)一步步检查下你的配置

**Comment by lxnxbnq** [comment]
你是对的，刚刚我检查了我的配置，犯了一个低级错误，没有在MainApplication.java中导入
 `new JSharePackage(SHUTDOWN_TOAST, SHUTDOWN_LOG)    // <--    Add JSharePackage`。谢谢
