### ISSUE TITLE
android上微信分享无缩略图

### ISSUE THREAD

**Issue by killdahehe** [jpush/jshare-react-native#96]

**Comment by JoshLipan** [comment]
不明白你要什么需求，可以截图看看

**Comment by killdahehe** [comment]
就是在安卓端分享链接到微信朋友圈和对话都没有图片，就是只显示链接的图标，ios正常

**Comment by wikieswan** [comment]
同样的问题求助。
android sdk 分享到微信朋友圈，不显示缩略图，分享到会话正常。
如图：
![image](https://user-images.githubusercontent.com/7147483/45545261-6406e980-b84c-11e8-9e50-1167120440d8.png)

代码如下
`
{
    type: 'link',
    url: `https://h5.shiyanzhushou.com/share/courses/${courseId}`,
    imageUrl: 'https://file.syzsstatic.com/h5/share/320.jpg',
    title: `${courseTitle}`,
    text: content,
  }

`
ps ios 一切正常

**Comment by JoshLipan** [comment]
你用的插件版本是？ @wikieswan

**Comment by killdahehe** [comment]
@JoshLipan 我用的"jshare-react-native": "1.3.3"

**Comment by JoshLipan** [comment]
此问题将在[极光社区](https://community.jiguang.cn/t/topic/29601)继续讨论

**Comment by JoshLipan** [comment]
微信链接缩略图Android端只支持传 imagePath 本地图片路径，不支持imageUrl网络路径。

**Comment by mengerzhuanyong** [comment]
"jcore-react-native": "^1.3.2",
"jshare-react-native": "^1.4.1",

使用的本地图片路径，分享出去之后也不显示图片！～
