### ISSUE TITLE
android 上微信取消分享返回 App 时闪退

### ISSUE THREAD

**Issue by arfaWong** [jpush/jshare-react-native#98]
正常分享流程可以走通，但是如果唤醒微信后点返回键时，App 闪退。是不是我哪里用得不对？

**Comment by JoshLipan** [comment]
可以看下闪退log

**Comment by arfaWong** [comment]
参数里面加上两个 callback 方法就好了。
另外，请问 log 要怎么抓？

**Comment by JoshLipan** [comment]
Android可以用adb命令比如：adb logcat -v time ->a.log
