### ISSUE TITLE
微博授权问题

### ISSUE THREAD

**Issue by lhh-sofy** [jpush/jshare-react-native#99]
授权的说明怎么是极光分享SDK啊，不应该是我自己的app名称么。。。
<img width="354" alt="fca0c11a-3c1c-48fa-adea-7039788d33a5" src="https://user-images.githubusercontent.com/13582183/45988912-dfb63100-c0ab-11e8-900e-246242b4c238.png">

**Comment by huangminlinux** [comment]
分享的 key 有没有替换成自己的

**Comment by lhh-sofy** [comment]
都替换掉了，包含RCTJShareConfig.plist以及info.plist

**Comment by huangminlinux** [comment]
URL Schemes 改了吗？

**Comment by lhh-sofy** [comment]
都改了。。。我在分享时候调用的。别的暂时未用此功能

**Comment by huangminlinux** [comment]
如果确定已经成功替换了，卸载重装然后 clean rebuild，试试。
